
spring:
  # **********************************************************************************************************
  #                                           Web: Static Resources
  # **********************************************************************************************************
  resources:
    chain:
      cache: false
      compressed: true
      strategy:
        content:
          enabled: true
          paths: /component/**

        fixed:
          enabled: true
          paths: /html/**,/js/**,/css/**
          version: ${random.uuid}

    cache:
      cachecontrol:
        #max-age: 1h
        #no-cache: true
        no-store: true
