
spring:
  # **********************************************************************************************************
  #                                           Web: Static Resources
  # **********************************************************************************************************
  resources:
    chain:
      cache: true
      compressed: true
      strategy:
        content:
          enabled: true
          paths: /js/**,/css/**

        fixed:
          enabled: true
          paths: /html/**
          version: ${random.uuid}

    cache:
      cachecontrol:
        max-age: 1h
        no-cache: true
        no-store: false
