
# ************************************************************************************************************
#                                             Server: ServerProperties
# ************************************************************************************************************
server:
  port: 9090

  compression:
    enabled: true
    min-response-size: 50KB

  servlet:
    context-path: /demo

    session:
      cookie:
        http-only: true
        secure: false

  tomcat:
    max-http-post-size: 4MB


spring:
  # **********************************************************************************************************
  #                                           Web: Template Engine
  # **********************************************************************************************************
  freemarker:
    enabled: true
    cache: true
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    requestContextAttribute: request


  # **********************************************************************************************************
  #                                           i18n: MessageSourceProperties
  # **********************************************************************************************************
  messages:
    basename: messages,config.i18n.messages

  # **********************************************************************************************************
  #                                           Web: File Upload
  # **********************************************************************************************************
  servlet:
    multipart:
      location: uploads/
      max-file-size: 10MB
      max-request-size: 12MB

  # **********************************************************************************************************
  #                                           Web: MVC
  # **********************************************************************************************************
  mvc:
    static-path-pattern: /resources/** # 设定 -> 静态资源 URL 访问路径
